### ISSUE TITLE
A playbar ficou presa em uma cor so + o menu e dificil de ver em Amoled mode

### ISSUE THREAD

**Issue by ghost** [Eeu2005/Playbar-Dynamic#1]
Oi! Por algum motivo, a extensão parou de mudar com as músicas e ficou presa em uma cor só, eu tentei desinstalar e instalar a extensão de novo mas nada muda.

![image](https://github.com/Eeu2005/Playbar-Dynamic/assets/171510941/80fc1376-3dfc-40b0-9a1c-bb9089753ef9)

![image](https://github.com/Eeu2005/Playbar-Dynamic/assets/171510941/dcd59886-9084-4171-9e90-6160755917e3)

Configs:

![image](https://github.com/Eeu2005/Playbar-Dynamic/assets/171510941/53ede1a5-0860-486e-9ddb-83386c022ee4)

Sem relação, mas no modo amoled você quase não consegue ver nada no menu de opções.

Adoraria se tivesse uma solucao! Eu amo essa extensao, fiz uma conta no GitHub so pra falar isso
Valeu

**Comment by Eeu2005** [comment]
Sabe ativar o modo desenvolvedor do spicetify?

**Comment by Eeu2005** [comment]
mais ou menos uma solução
- vá no terminal do PC e digite `spicetify enable-devtools`
- O Spotify ira reiniciar ou abrir (depende se ele já estava aberto)
-   Pressione Ctrl + Shift + I (Windows/Linux)  ou Cmd + Option + I (macOS)  no spotify
- nisso ira abrir um terminal igual de navegador:
![image](https://github.com/Eeu2005/Playbar-Dynamic/assets/135387034/f1c35b02-aa49-4605-b6ea-056f84f3c539)

igual a imagem digite `Spicetify.LocalStorage.remove('playbarConfig')`

isso vai deletar as configurações e as cores armazenadas

**Comment by ghost** [comment]
![image](https://github.com/Eeu2005/Playbar-Dynamic/assets/171510941/5db721b3-1007-4ea5-9f9f-2bf9aa87d659)

Tentei mas so recebi "undefined"

**Comment by Eeu2005** [comment]
mas funcionou?

**Comment by ghost** [comment]
Nao... a cor mudou pra um azul mas continua statica

![image](https://github.com/Eeu2005/Playbar-Dynamic/assets/171510941/ef399fde-1b9f-4387-aa5e-e856ba5318f0)

![image](https://github.com/Eeu2005/Playbar-Dynamic/assets/171510941/83cb67af-95e9-41a2-82e3-bfba45410275)

**Comment by Eeu2005** [comment]
os dois prints estao com a mesma musica

**Comment by ghost** [comment]
Ah foi mal

mas ainda assim ficou na mesma

![image](https://github.com/Eeu2005/Playbar-Dynamic/assets/171510941/bb9ea4ab-2f5a-4cea-a806-9a64b5305e19)
![image](https://github.com/Eeu2005/Playbar-Dynamic/assets/171510941/9b9cbfd5-363c-4cf4-81aa-45ecc3fd65df)

Ate tentei desinstalar e instalar a extensao de novo

**Comment by e391hed12** [comment]
![image](https://github.com/Eeu2005/Playbar-Dynamic/assets/171510941/9f6c4ad2-d39b-4093-a977-70859966ac1c)

Acabei de perceber uma mensagem, 

ReferenceError: Vibrant is not defined
    at pickCoverColor (default-dynamic.js?time=1717441622471:277:28)
    at registerCoverListener (default-dynamic.js?time=1717441622471:296:5)
    at default-dynamic.js?time=1717441622471:313:1

Talvez tenha alguma coisa a ver?

![image](https://github.com/Eeu2005/Playbar-Dynamic/assets/171510941/74d60501-1758-4dee-a3c9-4d63dd25207a)

**Comment by Eeu2005** [comment]
'deafult dynamic'  e do tema

**Comment by Eeu2005** [comment]
o meu vai tar "playbar dynamic"

**Comment by ghost** [comment]
Nevermind

**Comment by Eeu2005** [comment]
Que?

**Comment by ghost** [comment]
Quis dizer deixa pra la sobre a mensagem


Pena que ainda nao ta funcionando :/

**Comment by Eeu2005** [comment]
mas esse erro nao aparece com playbar dynamic?

**Comment by ghost** [comment]
Oi

Eu dei uma fucada e achei playbarConfig no localstorage direto

![image](https://github.com/Eeu2005/Playbar-Dynamic/assets/171510941/1b7420cc-cf3b-4b06-875d-472066d81f03)

O value e:

{"uriPassada":"https://i.scdn.co/image/ab67616d0000b2735011018cca4aa7091e08ae93","uriAtual":"https://i.scdn.co/image/ab67616d0000b27342ffc7773e7f4ea48e5606a8","corSpice":{"VIBRANT":"#fe01a0","undefined":"#010001","DESATURATED":"#0c5b95","LIGHT_VIBRANT":"#fe01a0","DARK_VIBRANT":"#fe01a0","VIBRANT_NON_ALARMING":"#fe01a0","PROMINENT":"#010001"},"escolhaSpice":"DESATURATED","input3color":false,"inputCorSpice":false,"curva":60,"corAtual":"#0c5b95","corPassada":"#010001"}

Daria pra eu editar isso manualmente ja q "remove" nao ta funcionando?

**Comment by Eeu2005** [comment]
Não  mas pelo value não ta pegando os novos códigos das musicas

**Comment by Eeu2005** [comment]
![image](https://github.com/Eeu2005/Playbar-Dynamic/assets/135387034/071fbb4b-4d3c-4b73-a9cb-1350a6786009)
### se não tiver assim ainda não atualizou 

se tiver atualizado e ainda bugado faz o seguinte 
![image](https://github.com/Eeu2005/Playbar-Dynamic/assets/135387034/198be94c-2fa9-455c-a068-44e4a6d34343)
`await fetchUris()`
`update()`

**Comment by ghost** [comment]
Atualizou mas ainda ta bugado e so da isso

![image](https://github.com/Eeu2005/Playbar-Dynamic/assets/171510941/fce123b0-653f-4247-a1f1-31d09f46046b)

xpui.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'operation')
    at xpui.js:1:3180419
    at h (vendor~xpui.js:1:3312825)
    at Generator.<anonymous> (vendor~xpui.js:1:3314167)
    at Generator.next (vendor~xpui.js:1:3313254)
    at r (vendor~xpui.js:1:3493837)
    at s (vendor~xpui.js:1:3494040)
    at vendor~xpui.js:1:3494099
    at new Promise (<anonymous>)
    at Object.<anonymous> (vendor~xpui.js:1:3493980)
    at Object.<anonymous> (xpui.js:1:3180663)

**Comment by Eeu2005** [comment]
Tenta ver se esses comandos que estao dando erro:
`const {fetchExtractedColors}= Spicetify.GraphQL.Definitions`
`await Spicetify.GraphQL.Request(fetchExtractedColors,{uris:Spicetify.Player.data.item.album.images[0].url})`

**Comment by Eeu2005** [comment]
opa gostaria de saber que tipo de erro deu nesses comando  que te passei
